Repository ie3-institute/powerflow, pull requests merged in 2025-05, with the labels that each got.

#219 Integration of semVer Gradle plugin
  CHANGELOG.md
  build.gradle
  gradle/scripts/semVer.gradle
  version.properties
Labels: enhancement, Ci

#222 Removing obsolete dependency constraint
  CHANGELOG.md
  build.gradle
Labels: dependencies

#205 Upgraded to `scala3`.
  CHANGELOG.md
  Jenkinsfile
  build.gradle
  gradle/scripts/scoverage.gradle
  src/main/scala/edu/ie3/powerflow/NewtonRaphsonPF.scala
Labels: dependencies

#230 Added dependabot workflow and CODEOWNERS
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/dependabot-auto-merge.yml
  CHANGELOG.md
Labels: dependencies, Ci
